// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: src/api/chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *GetAvailableUsersRequest) Reset() {
	*x = GetAvailableUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableUsersRequest) ProtoMessage() {}

func (x *GetAvailableUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableUsersRequest) Descriptor() ([]byte, []int) {
	return file_src_api_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailableUsersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetAvailableUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableUsers []*UserProfile `protobuf:"bytes,1,rep,name=availableUsers,proto3" json:"availableUsers,omitempty"`
}

func (x *GetAvailableUsersResponse) Reset() {
	*x = GetAvailableUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableUsersResponse) ProtoMessage() {}

func (x *GetAvailableUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableUsersResponse) Descriptor() ([]byte, []int) {
	return file_src_api_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableUsersResponse) GetAvailableUsers() []*UserProfile {
	if x != nil {
		return x.AvailableUsers
	}
	return nil
}

var File_src_api_chat_proto protoreflect.FileDescriptor

var file_src_api_chat_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x14, 0x73, 0x72, 0x63, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x58, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x32, 0x63, 0x0a, 0x0b, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1e,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_api_chat_proto_rawDescOnce sync.Once
	file_src_api_chat_proto_rawDescData = file_src_api_chat_proto_rawDesc
)

func file_src_api_chat_proto_rawDescGZIP() []byte {
	file_src_api_chat_proto_rawDescOnce.Do(func() {
		file_src_api_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_api_chat_proto_rawDescData)
	})
	return file_src_api_chat_proto_rawDescData
}

var file_src_api_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_api_chat_proto_goTypes = []interface{}{
	(*GetAvailableUsersRequest)(nil),  // 0: user.GetAvailableUsersRequest
	(*GetAvailableUsersResponse)(nil), // 1: user.GetAvailableUsersResponse
	(*Pagination)(nil),                // 2: common.Pagination
	(*UserProfile)(nil),               // 3: common.UserProfile
}
var file_src_api_chat_proto_depIdxs = []int32{
	2, // 0: user.GetAvailableUsersRequest.pagination:type_name -> common.Pagination
	3, // 1: user.GetAvailableUsersResponse.availableUsers:type_name -> common.UserProfile
	0, // 2: user.ChatService.GetAvailableUsers:input_type -> user.GetAvailableUsersRequest
	1, // 3: user.ChatService.GetAvailableUsers:output_type -> user.GetAvailableUsersResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_api_chat_proto_init() }
func file_src_api_chat_proto_init() {
	if File_src_api_chat_proto != nil {
		return
	}
	file_src_api_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_api_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_api_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_api_chat_proto_goTypes,
		DependencyIndexes: file_src_api_chat_proto_depIdxs,
		MessageInfos:      file_src_api_chat_proto_msgTypes,
	}.Build()
	File_src_api_chat_proto = out.File
	file_src_api_chat_proto_rawDesc = nil
	file_src_api_chat_proto_goTypes = nil
	file_src_api_chat_proto_depIdxs = nil
}
