# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import common_pb2 as api_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/chat.proto',
  package='user',
  syntax='proto3',
  serialized_options=b'Z\006/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61pi/chat.proto\x12\x04user\x1a\x10\x61pi/common.proto\"^\n\x04\x43hat\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x07userOne\x18\x02 \x01(\x0b\x32\x13.common.UserProfile\x12$\n\x07userTwo\x18\x03 \x01(\x0b\x32\x13.common.UserProfile\"B\n\x18GetAvailableUsersRequest\x12&\n\npagination\x18\x01 \x01(\x0b\x32\x12.common.Pagination\"H\n\x19GetAvailableUsersResponse\x12+\n\x0e\x61vailableUsers\x18\x01 \x03(\x0b\x32\x13.common.UserProfile\"9\n\x11\x43reateChatRequest\x12\x11\n\tuserOneId\x18\x01 \x01(\t\x12\x11\n\tuserTwoId\x18\x02 \x01(\t\".\n\x12\x43reateChatResponse\x12\x18\n\x04\x63hat\x18\x01 \x01(\x0b\x32\n.user.Chat2\xa4\x01\n\x0b\x43hatService\x12T\n\x11GetAvailableUsers\x12\x1e.user.GetAvailableUsersRequest\x1a\x1f.user.GetAvailableUsersResponse\x12?\n\nCreateChat\x12\x17.user.CreateChatRequest\x1a\x18.user.CreateChatResponseB\x08Z\x06/protob\x06proto3'
  ,
  dependencies=[api_dot_common__pb2.DESCRIPTOR,])




_CHAT = _descriptor.Descriptor(
  name='Chat',
  full_name='user.Chat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='user.Chat.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userOne', full_name='user.Chat.userOne', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userTwo', full_name='user.Chat.userTwo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=136,
)


_GETAVAILABLEUSERSREQUEST = _descriptor.Descriptor(
  name='GetAvailableUsersRequest',
  full_name='user.GetAvailableUsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pagination', full_name='user.GetAvailableUsersRequest.pagination', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=204,
)


_GETAVAILABLEUSERSRESPONSE = _descriptor.Descriptor(
  name='GetAvailableUsersResponse',
  full_name='user.GetAvailableUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='availableUsers', full_name='user.GetAvailableUsersResponse.availableUsers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=278,
)


_CREATECHATREQUEST = _descriptor.Descriptor(
  name='CreateChatRequest',
  full_name='user.CreateChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userOneId', full_name='user.CreateChatRequest.userOneId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userTwoId', full_name='user.CreateChatRequest.userTwoId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=337,
)


_CREATECHATRESPONSE = _descriptor.Descriptor(
  name='CreateChatResponse',
  full_name='user.CreateChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat', full_name='user.CreateChatResponse.chat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=385,
)

_CHAT.fields_by_name['userOne'].message_type = api_dot_common__pb2._USERPROFILE
_CHAT.fields_by_name['userTwo'].message_type = api_dot_common__pb2._USERPROFILE
_GETAVAILABLEUSERSREQUEST.fields_by_name['pagination'].message_type = api_dot_common__pb2._PAGINATION
_GETAVAILABLEUSERSRESPONSE.fields_by_name['availableUsers'].message_type = api_dot_common__pb2._USERPROFILE
_CREATECHATRESPONSE.fields_by_name['chat'].message_type = _CHAT
DESCRIPTOR.message_types_by_name['Chat'] = _CHAT
DESCRIPTOR.message_types_by_name['GetAvailableUsersRequest'] = _GETAVAILABLEUSERSREQUEST
DESCRIPTOR.message_types_by_name['GetAvailableUsersResponse'] = _GETAVAILABLEUSERSRESPONSE
DESCRIPTOR.message_types_by_name['CreateChatRequest'] = _CREATECHATREQUEST
DESCRIPTOR.message_types_by_name['CreateChatResponse'] = _CREATECHATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chat = _reflection.GeneratedProtocolMessageType('Chat', (_message.Message,), {
  'DESCRIPTOR' : _CHAT,
  '__module__' : 'api.chat_pb2'
  # @@protoc_insertion_point(class_scope:user.Chat)
  })
_sym_db.RegisterMessage(Chat)

GetAvailableUsersRequest = _reflection.GeneratedProtocolMessageType('GetAvailableUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETAVAILABLEUSERSREQUEST,
  '__module__' : 'api.chat_pb2'
  # @@protoc_insertion_point(class_scope:user.GetAvailableUsersRequest)
  })
_sym_db.RegisterMessage(GetAvailableUsersRequest)

GetAvailableUsersResponse = _reflection.GeneratedProtocolMessageType('GetAvailableUsersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETAVAILABLEUSERSRESPONSE,
  '__module__' : 'api.chat_pb2'
  # @@protoc_insertion_point(class_scope:user.GetAvailableUsersResponse)
  })
_sym_db.RegisterMessage(GetAvailableUsersResponse)

CreateChatRequest = _reflection.GeneratedProtocolMessageType('CreateChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHATREQUEST,
  '__module__' : 'api.chat_pb2'
  # @@protoc_insertion_point(class_scope:user.CreateChatRequest)
  })
_sym_db.RegisterMessage(CreateChatRequest)

CreateChatResponse = _reflection.GeneratedProtocolMessageType('CreateChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHATRESPONSE,
  '__module__' : 'api.chat_pb2'
  # @@protoc_insertion_point(class_scope:user.CreateChatResponse)
  })
_sym_db.RegisterMessage(CreateChatResponse)


DESCRIPTOR._options = None

_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='user.ChatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=388,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAvailableUsers',
    full_name='user.ChatService.GetAvailableUsers',
    index=0,
    containing_service=None,
    input_type=_GETAVAILABLEUSERSREQUEST,
    output_type=_GETAVAILABLEUSERSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateChat',
    full_name='user.ChatService.CreateChat',
    index=1,
    containing_service=None,
    input_type=_CREATECHATREQUEST,
    output_type=_CREATECHATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
