# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/api/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='src/api/common.proto',
    package='common',
    syntax='proto3',
    serialized_options=b'Z\006/proto',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14src/api/common.proto\x12\x06\x63ommon\"\x07\n\x05\x45mpty\"+\n\nJwtPayload\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"(\n\x0bUserProfile\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"+\n\nPagination\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x0f\n\x07perPage\x18\x02 \x01(\x05\"\x1f\n\x0ePaginationMeta\x12\r\n\x05total\x18\x01 \x01(\x05\x42\x08Z\x06/protob\x06proto3'
)


_EMPTY = _descriptor.Descriptor(
    name='Empty',
    full_name='common.Empty',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=32,
    serialized_end=39,
)


_JWTPAYLOAD = _descriptor.Descriptor(
    name='JwtPayload',
    full_name='common.JwtPayload',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='userId', full_name='common.JwtPayload.userId', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='email', full_name='common.JwtPayload.email', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=41,
    serialized_end=84,
)


_USERPROFILE = _descriptor.Descriptor(
    name='UserProfile',
    full_name='common.UserProfile',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='common.UserProfile.id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='email', full_name='common.UserProfile.email', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=86,
    serialized_end=126,
)


_PAGINATION = _descriptor.Descriptor(
    name='Pagination',
    full_name='common.Pagination',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='page', full_name='common.Pagination.page', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='perPage', full_name='common.Pagination.perPage', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=128,
    serialized_end=171,
)


_PAGINATIONMETA = _descriptor.Descriptor(
    name='PaginationMeta',
    full_name='common.PaginationMeta',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='total', full_name='common.PaginationMeta.total', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=173,
    serialized_end=204,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['JwtPayload'] = _JWTPAYLOAD
DESCRIPTOR.message_types_by_name['UserProfile'] = _USERPROFILE
DESCRIPTOR.message_types_by_name['Pagination'] = _PAGINATION
DESCRIPTOR.message_types_by_name['PaginationMeta'] = _PAGINATIONMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
    'DESCRIPTOR': _EMPTY,
    '__module__': 'api.common_pb2'
    # @@protoc_insertion_point(class_scope:common.Empty)
})
_sym_db.RegisterMessage(Empty)

JwtPayload = _reflection.GeneratedProtocolMessageType('JwtPayload', (_message.Message,), {
    'DESCRIPTOR': _JWTPAYLOAD,
    '__module__': 'api.common_pb2'
    # @@protoc_insertion_point(class_scope:common.JwtPayload)
})
_sym_db.RegisterMessage(JwtPayload)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), {
    'DESCRIPTOR': _USERPROFILE,
    '__module__': 'api.common_pb2'
    # @@protoc_insertion_point(class_scope:common.UserProfile)
})
_sym_db.RegisterMessage(UserProfile)

Pagination = _reflection.GeneratedProtocolMessageType('Pagination', (_message.Message,), {
    'DESCRIPTOR': _PAGINATION,
    '__module__': 'api.common_pb2'
    # @@protoc_insertion_point(class_scope:common.Pagination)
})
_sym_db.RegisterMessage(Pagination)

PaginationMeta = _reflection.GeneratedProtocolMessageType('PaginationMeta', (_message.Message,), {
    'DESCRIPTOR': _PAGINATIONMETA,
    '__module__': 'api.common_pb2'
    # @@protoc_insertion_point(class_scope:common.PaginationMeta)
})
_sym_db.RegisterMessage(PaginationMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
