# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import common_pb2 as api_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/user.proto',
  package='user',
  syntax='proto3',
  serialized_options=b'Z\006/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61pi/user.proto\x12\x04user\x1a\x10\x61pi/common.proto\"-\n\x0fJwtTokenPayload\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03ttl\x18\x02 \x01(\x05\"0\n\rSignUpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x0eSignUpResponse\x12&\n\x07payload\x18\x01 \x01(\x0b\x32\x15.user.JwtTokenPayload\">\n\x14UsersInternalRequest\x12&\n\npagination\x18\x01 \x01(\x0b\x32\x12.common.Pagination\"D\n\x15UsersInternalResponse\x12+\n\x0e\x61vailableUsers\x18\x01 \x03(\x0b\x32\x13.common.UserProfile2\xa6\x02\n\x0bUserService\x12\x33\n\x06SignUp\x12\x13.user.SignUpRequest\x1a\x14.user.SignUpResponse\x12\x33\n\x06SignIn\x12\x13.user.SignUpRequest\x1a\x14.user.SignUpResponse\x12-\n\x07Profile\x12\r.common.Empty\x1a\x13.common.UserProfile\x12\x34\n\x0fGetUserInternal\x12\x0c.common.ById\x1a\x13.common.UserProfile\x12H\n\rUsersInternal\x12\x1a.user.UsersInternalRequest\x1a\x1b.user.UsersInternalResponseB\x08Z\x06/protob\x06proto3'
  ,
  dependencies=[api_dot_common__pb2.DESCRIPTOR,])




_JWTTOKENPAYLOAD = _descriptor.Descriptor(
  name='JwtTokenPayload',
  full_name='user.JwtTokenPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='user.JwtTokenPayload.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='user.JwtTokenPayload.ttl', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=87,
)


_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignUpRequest',
  full_name='user.SignUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='user.SignUpRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.SignUpRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=137,
)


_SIGNUPRESPONSE = _descriptor.Descriptor(
  name='SignUpResponse',
  full_name='user.SignUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='user.SignUpResponse.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=195,
)


_USERSINTERNALREQUEST = _descriptor.Descriptor(
  name='UsersInternalRequest',
  full_name='user.UsersInternalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pagination', full_name='user.UsersInternalRequest.pagination', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=259,
)


_USERSINTERNALRESPONSE = _descriptor.Descriptor(
  name='UsersInternalResponse',
  full_name='user.UsersInternalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='availableUsers', full_name='user.UsersInternalResponse.availableUsers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=329,
)

_SIGNUPRESPONSE.fields_by_name['payload'].message_type = _JWTTOKENPAYLOAD
_USERSINTERNALREQUEST.fields_by_name['pagination'].message_type = api_dot_common__pb2._PAGINATION
_USERSINTERNALRESPONSE.fields_by_name['availableUsers'].message_type = api_dot_common__pb2._USERPROFILE
DESCRIPTOR.message_types_by_name['JwtTokenPayload'] = _JWTTOKENPAYLOAD
DESCRIPTOR.message_types_by_name['SignUpRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['SignUpResponse'] = _SIGNUPRESPONSE
DESCRIPTOR.message_types_by_name['UsersInternalRequest'] = _USERSINTERNALREQUEST
DESCRIPTOR.message_types_by_name['UsersInternalResponse'] = _USERSINTERNALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JwtTokenPayload = _reflection.GeneratedProtocolMessageType('JwtTokenPayload', (_message.Message,), {
  'DESCRIPTOR' : _JWTTOKENPAYLOAD,
  '__module__' : 'api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.JwtTokenPayload)
  })
_sym_db.RegisterMessage(JwtTokenPayload)

SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPREQUEST,
  '__module__' : 'api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUpRequest)
  })
_sym_db.RegisterMessage(SignUpRequest)

SignUpResponse = _reflection.GeneratedProtocolMessageType('SignUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPRESPONSE,
  '__module__' : 'api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUpResponse)
  })
_sym_db.RegisterMessage(SignUpResponse)

UsersInternalRequest = _reflection.GeneratedProtocolMessageType('UsersInternalRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERSINTERNALREQUEST,
  '__module__' : 'api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UsersInternalRequest)
  })
_sym_db.RegisterMessage(UsersInternalRequest)

UsersInternalResponse = _reflection.GeneratedProtocolMessageType('UsersInternalResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERSINTERNALRESPONSE,
  '__module__' : 'api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UsersInternalResponse)
  })
_sym_db.RegisterMessage(UsersInternalResponse)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='user.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=332,
  serialized_end=626,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignUp',
    full_name='user.UserService.SignUp',
    index=0,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_SIGNUPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SignIn',
    full_name='user.UserService.SignIn',
    index=1,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_SIGNUPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Profile',
    full_name='user.UserService.Profile',
    index=2,
    containing_service=None,
    input_type=api_dot_common__pb2._EMPTY,
    output_type=api_dot_common__pb2._USERPROFILE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserInternal',
    full_name='user.UserService.GetUserInternal',
    index=3,
    containing_service=None,
    input_type=api_dot_common__pb2._BYID,
    output_type=api_dot_common__pb2._USERPROFILE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UsersInternal',
    full_name='user.UserService.UsersInternal',
    index=4,
    containing_service=None,
    input_type=_USERSINTERNALREQUEST,
    output_type=_USERSINTERNALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
