# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/api/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.api import common_pb2 as src_dot_api_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/api/user.proto',
  package='user',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12src/api/user.proto\x12\x04user\x1a\x14src/api/common.proto\"-\n\x0fJwtTokenPayload\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03ttl\x18\x02 \x01(\x05\"0\n\rSignUpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x0eSignUpResponse\x12&\n\x07payload\x18\x01 \x01(\x0b\x32\x15.user.JwtTokenPayload2\xa6\x01\n\x0bUserService\x12\x33\n\x06SignUp\x12\x13.user.SignUpRequest\x1a\x14.user.SignUpResponse\x12\x33\n\x06SignIn\x12\x13.user.SignUpRequest\x1a\x14.user.SignUpResponse\x12-\n\x07Profile\x12\r.common.Empty\x1a\x13.common.UserProfileb\x06proto3'
  ,
  dependencies=[src_dot_api_dot_common__pb2.DESCRIPTOR,])




_JWTTOKENPAYLOAD = _descriptor.Descriptor(
  name='JwtTokenPayload',
  full_name='user.JwtTokenPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='user.JwtTokenPayload.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='user.JwtTokenPayload.ttl', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=95,
)


_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignUpRequest',
  full_name='user.SignUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='user.SignUpRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.SignUpRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=145,
)


_SIGNUPRESPONSE = _descriptor.Descriptor(
  name='SignUpResponse',
  full_name='user.SignUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='user.SignUpResponse.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=203,
)

_SIGNUPRESPONSE.fields_by_name['payload'].message_type = _JWTTOKENPAYLOAD
DESCRIPTOR.message_types_by_name['JwtTokenPayload'] = _JWTTOKENPAYLOAD
DESCRIPTOR.message_types_by_name['SignUpRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['SignUpResponse'] = _SIGNUPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JwtTokenPayload = _reflection.GeneratedProtocolMessageType('JwtTokenPayload', (_message.Message,), {
  'DESCRIPTOR' : _JWTTOKENPAYLOAD,
  '__module__' : 'src.api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.JwtTokenPayload)
  })
_sym_db.RegisterMessage(JwtTokenPayload)

SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPREQUEST,
  '__module__' : 'src.api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUpRequest)
  })
_sym_db.RegisterMessage(SignUpRequest)

SignUpResponse = _reflection.GeneratedProtocolMessageType('SignUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPRESPONSE,
  '__module__' : 'src.api.user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUpResponse)
  })
_sym_db.RegisterMessage(SignUpResponse)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='user.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=206,
  serialized_end=372,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignUp',
    full_name='user.UserService.SignUp',
    index=0,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_SIGNUPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SignIn',
    full_name='user.UserService.SignIn',
    index=1,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_SIGNUPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Profile',
    full_name='user.UserService.Profile',
    index=2,
    containing_service=None,
    input_type=src_dot_api_dot_common__pb2._EMPTY,
    output_type=src_dot_api_dot_common__pb2._USERPROFILE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
